# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_verbs_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Insert_VerbWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 455)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insert_verb_verb_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_verb_label.setFont(font)
        self.insert_verb_verb_label.setObjectName("insert_verb_verb_label")
        self.horizontalLayout.addWidget(self.insert_verb_verb_label)
        self.insert_verb_mverb_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_verb_mverb_lineEdit.setObjectName("insert_verb_mverb_lineEdit")
        self.horizontalLayout.addWidget(self.insert_verb_mverb_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.insert_verb_engmeaning_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_engmeaning_label.setFont(font)
        self.insert_verb_engmeaning_label.setObjectName("insert_verb_engmeaning_label")
        self.horizontalLayout_3.addWidget(self.insert_verb_engmeaning_label)
        self.insert_verb_engmeaning_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_verb_engmeaning_lineEdit.setObjectName("insert_verb_engmeaning_lineEdit")
        self.horizontalLayout_3.addWidget(self.insert_verb_engmeaning_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.insert_verb_hindimeaning_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_hindimeaning_label.setFont(font)
        self.insert_verb_hindimeaning_label.setObjectName("insert_verb_hindimeaning_label")
        self.horizontalLayout_4.addWidget(self.insert_verb_hindimeaning_label)
        self.insert_verb_hindimeaning_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_verb_hindimeaning_lineEdit.setObjectName("insert_verb_hindimeaning_lineEdit")
        self.horizontalLayout_4.addWidget(self.insert_verb_hindimeaning_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.insert_verb_satz_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_satz_label.setFont(font)
        self.insert_verb_satz_label.setObjectName("insert_verb_satz_label")
        self.horizontalLayout_5.addWidget(self.insert_verb_satz_label)
        self.insert_verb_satz_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_verb_satz_lineEdit.setObjectName("insert_verb_satz_lineEdit")
        self.horizontalLayout_5.addWidget(self.insert_verb_satz_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.insert_verb_level_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_level_label.setFont(font)
        self.insert_verb_level_label.setObjectName("insert_verb_level_label")
        self.horizontalLayout_6.addWidget(self.insert_verb_level_label)
        self.insert_verb_level_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_verb_level_comboBox.setFont(font)
        self.insert_verb_level_comboBox.setObjectName("insert_verb_level_comboBox")
        self.insert_verb_level_comboBox.addItem("")
        self.insert_verb_level_comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.insert_verb_level_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.insert_verb_type_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_type_label.setFont(font)
        self.insert_verb_type_label.setObjectName("insert_verb_type_label")
        self.horizontalLayout_7.addWidget(self.insert_verb_type_label)
        self.insert_verb_type_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_verb_type_comboBox.setFont(font)
        self.insert_verb_type_comboBox.setObjectName("insert_verb_type_comboBox")
        self.insert_verb_type_comboBox.addItem("")
        self.insert_verb_type_comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.insert_verb_type_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.insert_verb_subtype_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_subtype_label.setFont(font)
        self.insert_verb_subtype_label.setObjectName("insert_verb_subtype_label")
        self.horizontalLayout_8.addWidget(self.insert_verb_subtype_label)
        self.insert_verb_subtype_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_verb_subtype_comboBox.setFont(font)
        self.insert_verb_subtype_comboBox.setObjectName("insert_verb_subtype_comboBox")
        self.insert_verb_subtype_comboBox.addItem("")
        self.insert_verb_subtype_comboBox.addItem("")
        self.insert_verb_subtype_comboBox.addItem("")
        self.insert_verb_subtype_comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.insert_verb_subtype_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.insert_verb_case_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_case_label.setFont(font)
        self.insert_verb_case_label.setObjectName("insert_verb_case_label")
        self.horizontalLayout_9.addWidget(self.insert_verb_case_label)
        self.insert_verb_case_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_verb_case_comboBox.setFont(font)
        self.insert_verb_case_comboBox.setObjectName("insert_verb_case_comboBox")
        self.insert_verb_case_comboBox.addItem("")
        self.insert_verb_case_comboBox.addItem("")
        self.insert_verb_case_comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.insert_verb_case_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.insert_verb_inputpic_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.insert_verb_inputpic_label.setFont(font)
        self.insert_verb_inputpic_label.setObjectName("insert_verb_inputpic_label")
        self.horizontalLayout_10.addWidget(self.insert_verb_inputpic_label)
        self.insert_verb_inputpic_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_verb_inputpic_lineEdit.setObjectName("insert_verb_inputpic_lineEdit")
        self.horizontalLayout_10.addWidget(self.insert_verb_inputpic_lineEdit)
        self.insert_verb_browse_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_verb_browse_pushButton.setFont(font)
        self.insert_verb_browse_pushButton.setObjectName("insert_verb_browse_pushButton")
        self.horizontalLayout_10.addWidget(self.insert_verb_browse_pushButton)
        self.insert_verb_picpreview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_verb_picpreview_pushButton.setFont(font)
        self.insert_verb_picpreview_pushButton.setObjectName("insert_verb_picpreview_pushButton")
        self.horizontalLayout_10.addWidget(self.insert_verb_picpreview_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.insert_verb_img_label = QtWidgets.QLabel(self.centralwidget)
        self.insert_verb_img_label.setScaledContents(True)
        self.insert_verb_img_label.setObjectName("insert_verb_img_label")
        self.horizontalLayout_12.addWidget(self.insert_verb_img_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.insert_verb_submit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_verb_submit_pushButton.sizePolicy().hasHeightForWidth())
        self.insert_verb_submit_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.insert_verb_submit_pushButton.setFont(font)
        self.insert_verb_submit_pushButton.setObjectName("insert_verb_submit_pushButton")
        self.horizontalLayout_2.addWidget(self.insert_verb_submit_pushButton)
        self.insert_verb_reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_verb_reset_pushButton.sizePolicy().hasHeightForWidth())
        self.insert_verb_reset_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.insert_verb_reset_pushButton.setFont(font)
        self.insert_verb_reset_pushButton.setObjectName("insert_verb_reset_pushButton")
        self.horizontalLayout_2.addWidget(self.insert_verb_reset_pushButton)
        self.insert_verb_tabview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_verb_tabview_pushButton.sizePolicy().hasHeightForWidth())
        self.insert_verb_tabview_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.insert_verb_tabview_pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/insert_verbs_table_view/table_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insert_verb_tabview_pushButton.setIcon(icon)
        self.insert_verb_tabview_pushButton.setObjectName("insert_verb_tabview_pushButton")
        self.horizontalLayout_2.addWidget(self.insert_verb_tabview_pushButton)
        self.insert_verb_treeview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_verb_treeview_pushButton.sizePolicy().hasHeightForWidth())
        self.insert_verb_treeview_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.insert_verb_treeview_pushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/insert_verbs_tree_view/tree_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insert_verb_treeview_pushButton.setIcon(icon1)
        self.insert_verb_treeview_pushButton.setObjectName("insert_verb_treeview_pushButton")
        self.horizontalLayout_2.addWidget(self.insert_verb_treeview_pushButton)
        self.insert_verb_conj_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_verb_conj_pushButton.sizePolicy().hasHeightForWidth())
        self.insert_verb_conj_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.insert_verb_conj_pushButton.setFont(font)
        self.insert_verb_conj_pushButton.setObjectName("insert_verb_conj_pushButton")
        self.horizontalLayout_2.addWidget(self.insert_verb_conj_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.insert_verb_mverb_lineEdit, self.insert_verb_engmeaning_lineEdit)
        MainWindow.setTabOrder(self.insert_verb_engmeaning_lineEdit, self.insert_verb_hindimeaning_lineEdit)
        MainWindow.setTabOrder(self.insert_verb_hindimeaning_lineEdit, self.insert_verb_satz_lineEdit)
        MainWindow.setTabOrder(self.insert_verb_satz_lineEdit, self.insert_verb_level_comboBox)
        MainWindow.setTabOrder(self.insert_verb_level_comboBox, self.insert_verb_type_comboBox)
        MainWindow.setTabOrder(self.insert_verb_type_comboBox, self.insert_verb_subtype_comboBox)
        MainWindow.setTabOrder(self.insert_verb_subtype_comboBox, self.insert_verb_case_comboBox)
        MainWindow.setTabOrder(self.insert_verb_case_comboBox, self.insert_verb_inputpic_lineEdit)
        MainWindow.setTabOrder(self.insert_verb_inputpic_lineEdit, self.insert_verb_browse_pushButton)
        MainWindow.setTabOrder(self.insert_verb_browse_pushButton, self.insert_verb_picpreview_pushButton)
        MainWindow.setTabOrder(self.insert_verb_picpreview_pushButton, self.insert_verb_submit_pushButton)
        MainWindow.setTabOrder(self.insert_verb_submit_pushButton, self.insert_verb_reset_pushButton)
        MainWindow.setTabOrder(self.insert_verb_reset_pushButton, self.insert_verb_tabview_pushButton)
        MainWindow.setTabOrder(self.insert_verb_tabview_pushButton, self.insert_verb_treeview_pushButton)
        MainWindow.setTabOrder(self.insert_verb_treeview_pushButton, self.insert_verb_conj_pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Insert Verb"))
        self.insert_verb_verb_label.setText(_translate("MainWindow", "Verb"))
        self.insert_verb_engmeaning_label.setText(_translate("MainWindow", "English Meaning"))
        self.insert_verb_hindimeaning_label.setText(_translate("MainWindow", "Hindi Meaning"))
        self.insert_verb_satz_label.setText(_translate("MainWindow", "Satz"))
        self.insert_verb_level_label.setText(_translate("MainWindow", "Level"))
        self.insert_verb_level_comboBox.setItemText(0, _translate("MainWindow", "Upto B1"))
        self.insert_verb_level_comboBox.setItemText(1, _translate("MainWindow", "Above B1"))
        self.insert_verb_type_label.setText(_translate("MainWindow", "Type"))
        self.insert_verb_type_comboBox.setItemText(0, _translate("MainWindow", "Regular"))
        self.insert_verb_type_comboBox.setItemText(1, _translate("MainWindow", "Irregular"))
        self.insert_verb_subtype_label.setText(_translate("MainWindow", "Sub-type"))
        self.insert_verb_subtype_comboBox.setItemText(0, _translate("MainWindow", "Normal"))
        self.insert_verb_subtype_comboBox.setItemText(1, _translate("MainWindow", "Trennbar"))
        self.insert_verb_subtype_comboBox.setItemText(2, _translate("MainWindow", "Double Infinitiv"))
        self.insert_verb_subtype_comboBox.setItemText(3, _translate("MainWindow", "Modal"))
        self.insert_verb_case_label.setText(_translate("MainWindow", "Case"))
        self.insert_verb_case_comboBox.setItemText(0, _translate("MainWindow", "Akkusativ"))
        self.insert_verb_case_comboBox.setItemText(1, _translate("MainWindow", "Dativ"))
        self.insert_verb_case_comboBox.setItemText(2, _translate("MainWindow", "Weschel"))
        self.insert_verb_inputpic_label.setText(_translate("MainWindow", "Input Picture"))
        self.insert_verb_browse_pushButton.setText(_translate("MainWindow", "Browse"))
        self.insert_verb_picpreview_pushButton.setText(_translate("MainWindow", "Picture Preview"))
        self.insert_verb_img_label.setText(_translate("MainWindow", "TextLabel"))
        self.insert_verb_submit_pushButton.setText(_translate("MainWindow", "Submit"))
        self.insert_verb_reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.insert_verb_tabview_pushButton.setText(_translate("MainWindow", "Table View"))
        self.insert_verb_treeview_pushButton.setText(_translate("MainWindow", "Tree View"))
        self.insert_verb_conj_pushButton.setText(_translate("MainWindow", "Fill Conjugation"))
import gui_py.insert_verbs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Insert_VerbWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
