# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 400)
        MainWindow.setMinimumSize(QtCore.QSize(850, 400))
        MainWindow.setMaximumSize(QtCore.QSize(875, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_pic_study.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.main_img_label = QtWidgets.QLabel(self.frame_2)
        self.main_img_label.setMaximumSize(QtCore.QSize(450, 500))
        self.main_img_label.setText("")
        self.main_img_label.setPixmap(QtGui.QPixmap(":/learn_german/learn_german.jpg"))
        self.main_img_label.setScaledContents(True)
        self.main_img_label.setObjectName("main_img_label")
        self.gridLayout.addWidget(self.main_img_label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.main_heading_label = QtWidgets.QLabel(self.frame_3)
        self.main_heading_label.setGeometry(QtCore.QRect(20, 10, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.main_heading_label.setFont(font)
        self.main_heading_label.setObjectName("main_heading_label")
        self.main_options_comboBox = QtWidgets.QComboBox(self.frame_3)
        self.main_options_comboBox.setGeometry(QtCore.QRect(90, 110, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.main_options_comboBox.setFont(font)
        self.main_options_comboBox.setObjectName("main_options_comboBox")
        self.main_options_comboBox.addItem("")
        self.main_options_comboBox.addItem("")
        self.main_options_comboBox.addItem("")
        self.main_options_comboBox.addItem("")
        self.main_go_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.main_go_pushButton.setGeometry(QtCore.QRect(220, 220, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.main_go_pushButton.setFont(font)
        self.main_go_pushButton.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.main_go_pushButton.setObjectName("main_go_pushButton")
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 22))
        self.menubar.setObjectName("menubar")
        self.menuAdmin_Access = QtWidgets.QMenu(self.menubar)
        self.menuAdmin_Access.setTitle("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/admin_access/admin_access.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuAdmin_Access.setIcon(icon1)
        self.menuAdmin_Access.setObjectName("menuAdmin_Access")
        self.menuVerb = QtWidgets.QMenu(self.menuAdmin_Access)
        self.menuVerb.setObjectName("menuVerb")
        self.menuPreposition = QtWidgets.QMenu(self.menuAdmin_Access)
        self.menuPreposition.setObjectName("menuPreposition")
        self.menuAdjective = QtWidgets.QMenu(self.menuAdmin_Access)
        self.menuAdjective.setObjectName("menuAdjective")
        self.menuNoun = QtWidgets.QMenu(self.menuAdmin_Access)
        self.menuNoun.setObjectName("menuNoun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInsert_Verb = QtWidgets.QAction(MainWindow)
        self.actionInsert_Verb.setObjectName("actionInsert_Verb")
        self.actionSearch_Verb = QtWidgets.QAction(MainWindow)
        self.actionSearch_Verb.setObjectName("actionSearch_Verb")
        self.actionModify_Verb = QtWidgets.QAction(MainWindow)
        self.actionModify_Verb.setObjectName("actionModify_Verb")
        self.actionDelete_Verb = QtWidgets.QAction(MainWindow)
        self.actionDelete_Verb.setObjectName("actionDelete_Verb")
        self.actionInsert_Preposition = QtWidgets.QAction(MainWindow)
        self.actionInsert_Preposition.setObjectName("actionInsert_Preposition")
        self.actionSearch_Preposition = QtWidgets.QAction(MainWindow)
        self.actionSearch_Preposition.setObjectName("actionSearch_Preposition")
        self.actionModify_Preposition = QtWidgets.QAction(MainWindow)
        self.actionModify_Preposition.setObjectName("actionModify_Preposition")
        self.actionDelete_Preposition = QtWidgets.QAction(MainWindow)
        self.actionDelete_Preposition.setObjectName("actionDelete_Preposition")
        self.actionInsert_Adjective = QtWidgets.QAction(MainWindow)
        self.actionInsert_Adjective.setObjectName("actionInsert_Adjective")
        self.actionSearch_Adjective = QtWidgets.QAction(MainWindow)
        self.actionSearch_Adjective.setObjectName("actionSearch_Adjective")
        self.actionModify_Adjective = QtWidgets.QAction(MainWindow)
        self.actionModify_Adjective.setObjectName("actionModify_Adjective")
        self.actionDelete_Adjective = QtWidgets.QAction(MainWindow)
        self.actionDelete_Adjective.setObjectName("actionDelete_Adjective")
        self.actionInsert_Noun = QtWidgets.QAction(MainWindow)
        self.actionInsert_Noun.setObjectName("actionInsert_Noun")
        self.actionSearch_Noun = QtWidgets.QAction(MainWindow)
        self.actionSearch_Noun.setObjectName("actionSearch_Noun")
        self.actionModify_Noun = QtWidgets.QAction(MainWindow)
        self.actionModify_Noun.setObjectName("actionModify_Noun")
        self.actionDelete_Noun = QtWidgets.QAction(MainWindow)
        self.actionDelete_Noun.setObjectName("actionDelete_Noun")
        self.menuVerb.addAction(self.actionInsert_Verb)
        self.menuVerb.addAction(self.actionSearch_Verb)
        self.menuVerb.addAction(self.actionModify_Verb)
        self.menuVerb.addAction(self.actionDelete_Verb)
        self.menuPreposition.addAction(self.actionInsert_Preposition)
        self.menuPreposition.addAction(self.actionSearch_Preposition)
        self.menuPreposition.addAction(self.actionModify_Preposition)
        self.menuPreposition.addAction(self.actionDelete_Preposition)
        self.menuAdjective.addAction(self.actionInsert_Adjective)
        self.menuAdjective.addAction(self.actionSearch_Adjective)
        self.menuAdjective.addAction(self.actionModify_Adjective)
        self.menuAdjective.addAction(self.actionDelete_Adjective)
        self.menuNoun.addAction(self.actionInsert_Noun)
        self.menuNoun.addAction(self.actionSearch_Noun)
        self.menuNoun.addAction(self.actionModify_Noun)
        self.menuNoun.addAction(self.actionDelete_Noun)
        self.menuAdmin_Access.addAction(self.menuVerb.menuAction())
        self.menuAdmin_Access.addAction(self.menuPreposition.menuAction())
        self.menuAdmin_Access.addAction(self.menuAdjective.menuAction())
        self.menuAdmin_Access.addAction(self.menuNoun.menuAction())
        self.menuAdmin_Access.addAction(self.actionExit)
        self.menubar.addAction(self.menuAdmin_Access.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VocabsEasyy"))
        self.main_heading_label.setText(_translate("MainWindow", "What would you like to learn???"))
        self.main_options_comboBox.setToolTip(_translate("MainWindow", "Select option to start"))
        self.main_options_comboBox.setItemText(0, _translate("MainWindow", "Verbs"))
        self.main_options_comboBox.setItemText(1, _translate("MainWindow", "Prepositions"))
        self.main_options_comboBox.setItemText(2, _translate("MainWindow", "Adjectives"))
        self.main_options_comboBox.setItemText(3, _translate("MainWindow", "Nouns"))
        self.main_go_pushButton.setToolTip(_translate("MainWindow", "Start Learning!"))
        self.main_go_pushButton.setText(_translate("MainWindow", "Go Learn!!!"))
        self.menuVerb.setTitle(_translate("MainWindow", "Verb"))
        self.menuPreposition.setTitle(_translate("MainWindow", "Preposition"))
        self.menuAdjective.setTitle(_translate("MainWindow", "Adjective"))
        self.menuNoun.setTitle(_translate("MainWindow", "Noun"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInsert_Verb.setText(_translate("MainWindow", "Insert Verb"))
        self.actionSearch_Verb.setText(_translate("MainWindow", "Search Verb"))
        self.actionModify_Verb.setText(_translate("MainWindow", "Modify Verb"))
        self.actionDelete_Verb.setText(_translate("MainWindow", "Delete Verb"))
        self.actionInsert_Preposition.setText(_translate("MainWindow", "Insert Preposition"))
        self.actionSearch_Preposition.setText(_translate("MainWindow", "Search Preposition"))
        self.actionModify_Preposition.setText(_translate("MainWindow", "Modify Preposition"))
        self.actionDelete_Preposition.setText(_translate("MainWindow", "Delete Preposition"))
        self.actionInsert_Adjective.setText(_translate("MainWindow", "Insert Adjective"))
        self.actionSearch_Adjective.setText(_translate("MainWindow", "Search Adjective"))
        self.actionModify_Adjective.setText(_translate("MainWindow", "Modify Adjective"))
        self.actionDelete_Adjective.setText(_translate("MainWindow", "Delete Adjective"))
        self.actionInsert_Noun.setText(_translate("MainWindow", "Insert Noun"))
        self.actionSearch_Noun.setText(_translate("MainWindow", "Search Noun"))
        self.actionModify_Noun.setText(_translate("MainWindow", "Modify Noun"))
        self.actionDelete_Noun.setText(_translate("MainWindow", "Delete Noun"))
import gui_py.main_win


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
