# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mongo_login_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 203)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.access_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.access_label.setFont(font)
        self.access_label.setObjectName("access_label")
        self.horizontalLayout_4.addWidget(self.access_label)
        self.access_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.access_comboBox.setFont(font)
        self.access_comboBox.setObjectName("access_comboBox")
        self.access_comboBox.addItem("")
        self.access_comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.access_comboBox)
        self.done_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.done_pushButton.setFont(font)
        self.done_pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_4.addWidget(self.done_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.host_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.host_label.setFont(font)
        self.host_label.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.host_label.setObjectName("host_label")
        self.horizontalLayout.addWidget(self.host_label)
        self.host_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.host_lineEdit.setFont(font)
        self.host_lineEdit.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.host_lineEdit.setObjectName("host_lineEdit")
        self.horizontalLayout.addWidget(self.host_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.port_label.setFont(font)
        self.port_label.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.port_label.setObjectName("port_label")
        self.horizontalLayout_2.addWidget(self.port_label)
        self.port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.port_lineEdit.setFont(font)
        self.port_lineEdit.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.horizontalLayout_2.addWidget(self.port_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_pushButton.setFont(font)
        self.reset_pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout_3.addWidget(self.reset_pushButton)
        self.login_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.login_pushButton.setObjectName("login_pushButton")
        self.horizontalLayout_3.addWidget(self.login_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.access_comboBox, self.host_lineEdit)
        MainWindow.setTabOrder(self.host_lineEdit, self.port_lineEdit)
        MainWindow.setTabOrder(self.port_lineEdit, self.reset_pushButton)
        MainWindow.setTabOrder(self.reset_pushButton, self.login_pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log In "))
        self.access_label.setText(_translate("MainWindow", "Do you have admin access?"))
        self.access_comboBox.setItemText(0, _translate("MainWindow", "No"))
        self.access_comboBox.setItemText(1, _translate("MainWindow", "Yes"))
        self.done_pushButton.setText(_translate("MainWindow", "Done"))
        self.host_label.setText(_translate("MainWindow", "Host"))
        self.port_label.setText(_translate("MainWindow", "Port"))
        self.reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.login_pushButton.setText(_translate("MainWindow", "Log In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
