# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_verb_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search_VerbWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 190)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_verb_by_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.search_verb_by_label.setFont(font)
        self.search_verb_by_label.setObjectName("search_verb_by_label")
        self.horizontalLayout.addWidget(self.search_verb_by_label)
        self.search_verb_by_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_verb_by_comboBox.setFont(font)
        self.search_verb_by_comboBox.setObjectName("search_verb_by_comboBox")
        self.search_verb_by_comboBox.addItem("")
        self.search_verb_by_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.search_verb_by_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_verb_search_text_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.search_verb_search_text_label.setFont(font)
        self.search_verb_search_text_label.setObjectName("search_verb_search_text_label")
        self.horizontalLayout_2.addWidget(self.search_verb_search_text_label)
        self.search_verb_searchbar_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_verb_searchbar_lineEdit.setObjectName("search_verb_searchbar_lineEdit")
        self.horizontalLayout_2.addWidget(self.search_verb_searchbar_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_verb_show_record_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_verb_show_record_pushButton.sizePolicy().hasHeightForWidth())
        self.search_verb_show_record_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_verb_show_record_pushButton.setFont(font)
        self.search_verb_show_record_pushButton.setObjectName("search_verb_show_record_pushButton")
        self.horizontalLayout_3.addWidget(self.search_verb_show_record_pushButton)
        self.search_verb_tabview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_verb_tabview_pushButton.sizePolicy().hasHeightForWidth())
        self.search_verb_tabview_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_verb_tabview_pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/table/search_table_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_verb_tabview_pushButton.setIcon(icon)
        self.search_verb_tabview_pushButton.setObjectName("search_verb_tabview_pushButton")
        self.horizontalLayout_3.addWidget(self.search_verb_tabview_pushButton)
        self.search_verb_treeview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_verb_treeview_pushButton.sizePolicy().hasHeightForWidth())
        self.search_verb_treeview_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_verb_treeview_pushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tree/search_tree_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_verb_treeview_pushButton.setIcon(icon1)
        self.search_verb_treeview_pushButton.setObjectName("search_verb_treeview_pushButton")
        self.horizontalLayout_3.addWidget(self.search_verb_treeview_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Search Verb"))
        self.search_verb_by_label.setText(_translate("MainWindow", "Search by"))
        self.search_verb_by_comboBox.setItemText(0, _translate("MainWindow", "German Verb"))
        self.search_verb_by_comboBox.setItemText(1, _translate("MainWindow", "English Name"))
        self.search_verb_search_text_label.setText(_translate("MainWindow", "Search Text"))
        self.search_verb_show_record_pushButton.setText(_translate("MainWindow", "Show Record"))
        self.search_verb_tabview_pushButton.setText(_translate("MainWindow", "Table View"))
        self.search_verb_treeview_pushButton.setText(_translate("MainWindow", "Tree View"))
import gui_py.table_view


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Search_VerbWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
